version: '3.3'
services:


  mysql:
    image: mysql
    container_name: mysqlPizza
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: makss
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: pizza
      MYSQL_ROOT_PASSWORD: 123


  application:
    image: app2
    container_name: myProjectEE
    ports:
      - "8080:8080"
    links:
      - mysql